### PR TITLE
Add dropdown select to filters for usability improvement

### PR DESCRIPTION
**Pull request by akizor**
Added dropdown select for filters for better usability. It's easier to just click a filter than typing it. The typing filter remains active if you want to do complex filtering.

### CODE REVIEW

**Comment by phatsk** [comment]
Can this support multiple selects? For example: is:arc is:primary

**Comment by akizor** [comment]
Right now no, but it's easy to make and actually a good advice. Although, the layout must be a bit changed because the multiselect tag requires much bigger page space than that mini header select.

**Comment by phatsk** [comment]
I think this should definitely be considered as an enhancement - one of the things that makes filters so powerful is the ability to combine them, and this might detract from people thinking they can use more than one at a time.

**Comment by akizor** [comment]
Will rethink this a bit and return with news.

**Comment by phatsk** [comment]
Fantastic - I like the way this is looking though - something similar to an autocomplete could also really help, and perhaps "tagging" filters once a valid one is selected?

**Comment by akizor** [comment]
Nice "tagging" idea. Will solve filter selection and allow filter combinations ;)

**Comment by SunburnedGoose** [comment]
btw, did you notice that clicking on the "Filter" label gave you a dropdown with all the filters and their descriptions?  Clicking on a filter added it to the dropdown.

**Comment by kyleshay** [comment]
token input would be really nice.

another thought - auto complete for the input box
https://imgur.com/ypv9wzL

**Comment by phatsk** [comment]
Well dang, that's pretty nifty! Maybe just a streamlining of the design of the filter window and a more prominent call to click on "Filters" next to search - some kind of iconography?

**Comment by akizor** [comment]
@SunburnedGoose i know "Filters" text still show the modal. I left everything as it was. Just added the select tag and hooked to existing functions, nothing to fancy.
Although this topic will certainly give birth to the next generation filters :)

**Comment by SunburnedGoose** [comment]
Sounds great.  Just raising awareness of the filter link.  It was just liplstik on a pig though.  

We've been thinking about what is the ideal solution for filters that works well across phones and desktop applications.

Is it a dropdown that has a grid of icons, arranged by like icons in rows? Packmule has a drawer with their filters; takes up too much space.  Tower Ghost uses a collection of dropdowns; runs out of horizontal space and forces you to scroll when in a phone.

**Comment by phatsk** [comment]
Could do a scrollable dropdown with checkboxes. On a phone display, it could be a full-screen experience with each row tappable to turn the filter on or off (display the same checkbox state as desktop).

**Pull request closed without merging**
