### PR TITLE
Enhancement: Filter by Weapon Type (not Class) #94

### PR DESCRIPTION
**Pull request by phatsk**
This pull request addresses the ability to filter by weapon type, also includes 

* priamryweaponengram
* specialweaponengram
* heavyweaponengram 

Not sure if you want those too, but they are there.

**N.B.** Sidearm is not yet included as we don't know the final in-data name (if we do and I don't know, my bad. It's an easy addition)

### CODE REVIEW

**Comment by phatsk** [comment]
Also, sorry about the tabs/spaces. What editor settings are you using?

**Comment by SunburnedGoose** [comment]
2 spaces afaik.  I'll review this tonight.  Thanks for the effort!

**Comment by SunburnedGoose** [comment]
btw, can you change the target branch to 'dev' instead of master?  

http://stackoverflow.com/questions/24159036/how-to-modify-a-pull-request-on-github-to-change-target-branch-to-merge-into

**Comment by phatsk** [comment]
Closing, pull moved to **dev**

**Pull request closed without merging**
