### PR TITLE
Add ZamTooltips for DestinyDB tooltips on hover

### PR DESCRIPTION
**Pull request by joshhunt**
This adds DestinyDB tooltips on item hover.

I had to make slight changes to the tooltips.js to make it work within the chrome extension (just make sure the protocol used is https).

I wasn't able to bundle tooltips.js into vendor.min.js - when i added it and ran `node min.js` everything in the app broke.

Thoughts?

### CODE REVIEW

**Comment by SunburnedGoose** [comment]
Can you close this and reopen it with the dev branch?

**Comment by joshhunt** [comment]
Of course.

**Comment by SunburnedGoose** [comment]
Thanks.

**Comment by SunburnedGoose** [comment]
I wanted to get these thoughts down before I lose them. 

1. Can you spawn the popup near the corners of the item box so it doesn't move around the box?  It's distracting when the popup scoots around the page as it runs away from the mouse.
2. The popup will flash when I move my mouse to the move popup box.  The white border of the item above is getting the mouseover.  Can you move the movePopup box closer to the item to avoid the inadvertent popup?
3. Touch users?  How do they get the benefit?

**Comment by SunburnedGoose** [comment]
Also that node min.js is just a one off thing.  I really need to get the task runner back into this and make it legitimate.

**Pull request closed without merging**
