### PR TITLE
Display storage blocks as columns

### PR DESCRIPTION
**Pull request by chrisfried**
screenshot 2015-03-05 08 54 31

### CODE REVIEW

**Comment by kyleshay** [comment]
that's some sweet CSS wizardry, let's go with it for now.

**Comment by kyleshay** [comment]
there are some issues when the page width goes to a much larger size. I plan on eventually re-working the page so that WEPAONS instead will be PRIMARY, SECONDARY, HEAVY, etc... I'm thinking it should be a 3x3 grid...(playing with the idea of showing a placeholder spot, like it does on the Destiny UI... maybe as a toggle.) so we'll have within each character two of those .sections side by side, then new ones on the next line down...

does that make sense?

**Comment by chrisfried** [comment]
Yeah. I've been working through some thoughts on the UI, as well. Going to post the mockup I have over on the subreddit.

**Comment by kyleshay** [comment]
That's great! 

Some people have suggested toggles and such. 

I'll have to start a reddit post or something for dev's looking to contribute, that way we're all going toward the same thing.

Thanks so much for contributing. I'll have to update the reddit post & window.html and be sure to add you and others in!

**Pull request merged**
