### PR TITLE
Line up vault section headers with guardian inventory headers.

### PR DESCRIPTION
**Pull request by chrisfried**
Before:
screenshot 2015-05-15 16 36 30
After:
screenshot 2015-05-15 16 36 01

### CODE REVIEW

**Comment by chrisfried** [comment]
General is a pain in the current state:
screenshot 2015-05-15 16 43 13

**Comment by SunburnedGoose** [comment]
The vault can be larger than the characters, so we don't make the vault 'sticky' in the same way we do the characters.  We do this because of feedback about the page length.  I'll hold on to this when we make a proper options page.

**Comment by SunburnedGoose** [comment]
Also, the changes to the function created a bug.  With your function, you can increase your height, but it doesn't go down when you reduce make the needed space smaller.

Moving the green heavy in the third character to the second character doesn't reduce the height.  The code I wrote accommodated for that by calculating by children.

**Comment by chrisfried** [comment]
The height issue is why only the overall sections are aligned, allowing the vault to remain internally compact.

**Comment by SunburnedGoose** [comment]
It isn't compact if it leaves space at the bottom. Setting min-heights
never lets it shrunk.

**Comment by chrisfried** [comment]
If the inventories are taller, there should be space at the bottom of each vault section.

**Comment by chrisfried** [comment]
Oh, you meant the glitch I introduced making space. That I agree with.

**Comment by SunburnedGoose** [comment]
Yeah. We kept 20px ish margin at the bottom of each type. I shouldn't be
working while in the drive thru

**Comment by chrisfried** [comment]
Fixed the bug I introduced.

**Comment by SunburnedGoose** [comment]
Thanks.  So what's your thoughts on getting rid of this JS manipulation all together and relying on the HTML/CSS alone to manage the heights?

**Comment by chrisfried** [comment]
It's not a bad idea, but it still requires restructuring of the HTML. Which I'm not volunteering for...

**Comment by SunburnedGoose** [comment]
I'll update dev branch w/ a version of this that works with all the item categories/types between guardians and the vault.

**Comment by SunburnedGoose** [comment]
I also made subclasses visibility hidden in the vault to keep things lined up so primary matches primary, etc.

**Comment by chrisfried** [comment]
Looks good.

**Comment by chrisfried** [comment]
Restored and reopened, re: #136.

**Comment by SunburnedGoose** [comment]
I'll merge this tonight and add a fifth column to the vault.

**Pull request closed without merging**
