### PR TITLE
Issue #130 - clean up filters, address not: filter

### PR DESCRIPTION
**Pull request by phatsk**
* Clean up and compartmentalize filter code. 
* Adds `not:` filter

### CODE REVIEW

**Comment by SunburnedGoose** [comment]
Thanks. I'll check this out tomorrow.

**Comment by phatsk** [comment]
Heh getting some much-deserved play time in?

**Comment by SunburnedGoose** [comment]
Oh, just some family time today. Then some Game of Thrones, and then 10
hours of sleep.  Sleeeeeeeep.

**Comment by SunburnedGoose** [comment]
Okay, there are several PR's on search.  #120 Stackable, #119 Weapon Types, and now this refactoring.  I don't think it is safe to pull them down.  Can you combine them into this PR so I can have a safe pull to test, and then complete the PR?

**Comment by phatsk** [comment]
Sorry for the delay - I'll be on this weekend (granted ToO doesn't take too much time)

**Comment by SunburnedGoose** [comment]
Thanks!

**Comment by phatsk** [comment]
I'm closing my previous PRs and starting back with the refactoring at Issue 170. Eventually stacked and weapon type will be added (probably tomorrow). I've been bogged down lately.

**Comment by phatsk** [comment]
And closing this one

**Pull request closed without merging**
