### PR TITLE
DIM complete redesign

### PR DESCRIPTION
**Pull request by kitsunekyo**
# Intro
See my post on reddit: https://www.reddit.com/r/DestinyTheGame/comments/3dw0fy/destiny_item_manager_redesign_xpost_from/

I spent the whole last 4 days redesigning our beloved Destiny Item Manager Chrome extension. I am not the creator, I merely forked it on github and put in some nights to make it visually more appealing (no offence kyleshay :P )

# Functionality Change
None. Everything works like before. 
Only the move-popup now shows item stats.
And I toned down the (still prominent) memory leak by switching more images to local assets instead of http requests.

# Style Changes (the big one)
* Added bootstrap grid styling (css added)
* Added bootstrap panel styling
* Replaced PNG icons with font-awesome font for cleaner rendering (and they have fucking awesome icons haha)
* Changed Markup on several positions to support column styling (col-xs-12 etc added)
* Item Icons now scale with browser width - for future mobile port
* New move-popup for items to show more information and better UX
* Slight redesign of Loadout UI

## Change to move-popup
The popup previously didnt show that much information to the user and I also wanted to try a new approach with the interface.

### General
* Panel reskinned
* Thumbnail added to the popup
* Size automatically adjusted for smaller or bigger popup (depending on amount of info)
* Unavailable interaction buttons hidden

### Weapons
Weapons UI

* Elemental Type no longer defines background but now shows up as icon
* Attack value now shown in sub-headline
* Weapon stats now displayed to quickly compare your stuff outside of destiny
* Added Markup to Locations and buttons for cleaner UX

### Armor
Armor UI

* Is now visually clearly different from weapons
* Shows Main stats in sub headline (i want to move the light level there as well)
* Smaller width due to less info shown

### General
General UI

* only shows store options and hides locations without interaction options
* ToDo: Add count to the panel and allow user to specify how much he wants to transfer

### CODE REVIEW

**Comment by SunburnedGoose** [comment]
Nice work. There is a lot of effort here. I'll check it when I'm later
tonight.

**Comment by kitsunekyo** [comment]
i unfortunately dont have the separate commits because i was working directly in the main repo and only have them locally. is there a way to migrate them to my fork? is maybe a little bit better to look through my changes.

**Comment by kitsunekyo** [comment]
thanks. i know. i am pretty new to git and by working on the main repo before and then copying it over to my fork I dont have all my individual commits displayed. since its not gonna be used its probably alright^^

**Comment by SunburnedGoose** [comment]
Let's transition this conversation to individual issues for each change in the PR.  We can work through them and get them into the application.

**Pull request closed without merging**
