### PR TITLE
Add new filters for is:locked and is:unlocked

### PR DESCRIPTION
**Pull request by bhollis**
Filter by whether or not the item is locked. Unlockable items are always filtered out.

### CODE REVIEW

**Comment by bhollis** [comment]
I added another commit which shows a "lock" icon on the item tooltip if the item is locked:

image
image

**Comment by Subject22** [comment]
Does the API support actually locking and unlocking items? DIM could support that, but I suppose unlocking items is potentially dangerous.

**Comment by SunburnedGoose** [comment]
We can.

**Comment by bhollis** [comment]
Sure, the API supports it, but this is just for displaying the status.

**Comment by Subject22** [comment]
Cool :)

**Comment by SunburnedGoose** [comment]
Looks great.  I'll commit it.

**Comment by SunburnedGoose** [comment]
btw, The PR is against the master branch.  If I pull this and merge it myself to dev, I dunno if it will maintain your commits.  I'll try this and see.

**Comment by SunburnedGoose** [comment]
commits added to dev, 
https://github.com/kyleshay/DIM/commits/dev

It's queued for v3.1.
I'll close this.

**Comment by bhollis** [comment]
Are we supposed to develop against `dev`? You might want to add a `CONTRIBUTING.md` or add something to the `README.md` about that.

**Comment by SunburnedGoose** [comment]
Yeah.  That's been on the list for a bit.

**Comment by bhollis** [comment]
Add an issue! Let other folks do it :-)

**Comment by SunburnedGoose** [comment]
+1

**Pull request closed without merging**
