### PR TITLE
Show a thin loading bar under the header instead of a loading spinner

### PR DESCRIPTION
**Pull request by bhollis**
This swaps out the progress tracker for the totally automatic `angular-loading-bar`, which shows a nice thin YouTube-style loading bar based on outstanding HTTP requests.

`angular-loading-bar` itself could use some work, but I figure I'll just contribute fixes directly to that project and we can benefit from them.

dim-loading

### CODE REVIEW

**Comment by bhollis** [comment]
Imgur link: http://imgur.com/4HbsieW

**Comment by SunburnedGoose** [comment]
Progress indicator tracks promises, not just http. Does it support
attaching multiple promises like the current tracker does and wait until
they all resolve?

Why do we need a cosmetic change to the indicator? What are you trying to
tell the user that they are not getting from the current solution?

I don't care for the pulsing of the indicator for each request. A Loadouts
can easily have two hundred or more requests for an absurdly large
Loadouts.

I'm interested in your thoughts on this. At the moment, the only thing I
would like to have on the app is a well that shows the current items being
moved so it is more transparent to the end user what is happening.

**Comment by bhollis** [comment]
The spinner is indeterminate with regard to progress - it just spins and spins until everything is done. A progress bar would show how much work we have to complete. Unfortunately `angular-promise-tracker` can't track progress - it only tracks whether *anything* is happening at all. I agree that the "pulsing" isn't great - as I mentioned, I think there are lots of improvements to be made to `angular-loading-bar` in order to make this really smooth (and, I think, some performance improvements that need to be made to DIM).

This particular library doesn't track promises - it uses an interceptor to track HTTP requests. My logic is that HTTP requests are the only thing that should take a significant amount of time in the tool, so a progress bar that works on that should be OK, and we can show partial progress for promises that make multiple requests in sequence. Are we doing a lot of waiting or other slow operations that aren't HTTP requests?

Alternately, I could whip up our own progress bar implementation that works on promises where we can tell it ahead of time that we have a sequence of X requests to do, though it'll be more complicated.

**Comment by SunburnedGoose** [comment]
We do not generate a move plan for loadouts or when items are moved. We
don't have any idea how the transfers will create new transfers to ensure a
successful move. Worse still are users who run multiple loadout and move
operations at the same time. DIM really needs a queue system.

So we use a promise as the container at the inception of the user intent,
and the promise is maintained until it is completed and the item has been
moved on screen. That is what we need tracked.

An example of a slow operation... We're going to add dialogs to the
operations when moving stacks so the promise will have pauses while the
user interacts with the dialogs. The move operation would still be in
progress while we wait.

The loading bar will only show incremental progress that gives the users no
sense of scope. That's the issue here. The spinner has the same problem.
I'd rather fix the problem of showing the users the scope of the operation
than a cosmetic change that has little impact. To compensate for this lack
of info, I show the toasters when items are successfully moved (or not for
loadouts).

We can talk through how to show users their current transfer scope in an
issue. When I get near a PC, I'll make one of there already isn't one.

**Comment by bhollis** [comment]
I guess I got too excited about contributing - I should have opened an RFC issue first. Certainly I agree that a queue for move operations would make this a lot more useful. Knowing exactly what's happening and is in the queue isn't super important to me, but having a general idea of how much work is pending is useful. Just let me know how you want it to work and I can make it happen.

**Comment by SunburnedGoose** [comment]
https://github.com/kyleshay/DIM/issues/161

**Pull request closed without merging**
